baseURL = "https://www.jamesrdevries.com/blog/"
title = "Things I'm Learning"
theme = "HugoTeX"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Params.author]
  name = "James DeVries"
  abstract = """
  These are my terse recordings to keep track of things I'm learning.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true
